"""
sahih_al_bukhari.bukhari
========================
Python library for Sahih al-Bukhari.

Data source priority (first match wins):
  1. data_path kwarg          →  Bukhari(data_path="/your/bukhari.json")
  2. bin/bukhari.json         →  the shared file at the repo root (auto-detected)
  3. jsDelivr CDN             →  fallback when installed standalone via pip

The shared file layout (monorepo root):
  bin/
    bukhari.json    ← single source of truth for BOTH JS and Python
  chapters/
    meta.json       ← generated by `node build.mjs`, used by CDN loader
    1.json
    2.json
    ...

API mirrors the npm package exactly (camelCase method names):
    bukhari = Bukhari()
    bukhari.get(1)
    bukhari.getByChapter(1)
    bukhari.search("prayer")
    bukhari.getRandom()
    bukhari[0]
    bukhari.length
    bukhari.metadata
    bukhari.chapters
"""

from __future__ import annotations

import json
import random
import threading
from pathlib import Path
from typing import Callable, Dict, Iterator, List, Optional, Union

import requests

CDN_BASE = "https://cdn.jsdelivr.net/npm/sahih-al-bukhari@3.1.1/chapters"

# ── Shared data file resolution ───────────────────────────────────────────────
# When installed from the monorepo (development / editable install), walk up
# from this file to find bin/bukhari.json at the repo root.
# Layout: <repo>/sahih_al_bukhari/bukhari.py → <repo>/bin/bukhari.json
_THIS_DIR   = Path(__file__).parent          # sahih_al_bukhari/
_REPO_ROOT  = _THIS_DIR.parent               # repo root (sahih-al-bukhari/)
_SHARED_JSON = _REPO_ROOT / "bin" / "bukhari.json"

# ── Per-path cache (each unique source gets its own cache entry) ──────────────
_cache: Dict[str, "_Store"] = {}
_lock  = threading.Lock()


# ---------------------------------------------------------------------------
# Data containers — attribute names mirror JS object keys exactly
# ---------------------------------------------------------------------------

class Hadith:
    """
    A single hadith.

    Attributes match JS object keys:
        .id          int
        .chapterId   int
        .arabic      str
        .english     dict   {"narrator": ..., "text": ...}
        .narrator    str    shortcut → english["narrator"]
        .text        str    shortcut → english["text"]
    """

    def __init__(self, data: dict):
        self._data           = data
        self.id: int         = data.get("id", 0)
        self.chapterId: int  = data.get("chapterId", 0)
        self.arabic: str     = data.get("arabic", "")
        _en                  = data.get("english") or {}
        self.english: dict   = _en
        self.narrator: str   = _en.get("narrator", "")
        self.text: str       = _en.get("text", "")

    def to_dict(self) -> dict:
        return self._data

    def __repr__(self) -> str:
        preview = self.text[:80] + "…" if len(self.text) > 80 else self.text
        return f"<Hadith id={self.id} chapterId={self.chapterId} text={preview!r}>"


class Chapter:
    """
    A chapter.

    Attributes:
        .id       int
        .arabic   str
        .english  str
    """

    def __init__(self, data: dict):
        self._data        = data
        self.id: int      = data.get("id", 0)
        self.arabic: str  = data.get("arabic", "")
        self.english: str = data.get("english", "")

    def to_dict(self) -> dict:
        return self._data

    def __repr__(self) -> str:
        return f"<Chapter id={self.id} english={self.english!r}>"


class Metadata:
    """
    Collection metadata.

    Attributes:
        .id       int
        .length   int
        .arabic   dict   {"title": ..., "author": ..., "introduction": ...}
        .english  dict   {"title": ..., "author": ..., "introduction": ...}
    """

    def __init__(self, data: dict):
        self._data         = data
        self.id: int       = data.get("id", 0)
        self.length: int   = data.get("length", 0)
        self.arabic: dict  = data.get("arabic") or {}
        self.english: dict = data.get("english") or {}

    def to_dict(self) -> dict:
        return self._data

    def __repr__(self) -> str:
        return (
            f"<Metadata title={self.english.get('title')!r}"
            f" author={self.english.get('author')!r}>"
        )


# ---------------------------------------------------------------------------
# Internal storage
# ---------------------------------------------------------------------------

class _Store:
    def __init__(self, hadiths: List[Hadith], chapters: List[Chapter], metadata: Metadata):
        self.hadiths  = hadiths
        self.chapters = chapters
        self.metadata = metadata
        self._by_id: Dict[int, Hadith]            = {h.id: h for h in hadiths}
        self._by_chapter: Dict[int, List[Hadith]] = {}
        for h in hadiths:
            self._by_chapter.setdefault(h.chapterId, []).append(h)


# ---------------------------------------------------------------------------
# Public class
# ---------------------------------------------------------------------------

class Bukhari:
    """
    Complete Sahih al-Bukhari collection.

    Data source (first match wins):
      1. data_path kwarg   →  explicit local file
      2. bin/bukhari.json  →  shared monorepo file (auto-detected)
      3. jsDelivr CDN      →  fallback for standalone pip installs

    Cache: each unique resolved path gets its own cache entry so multiple
    instances with different paths work independently.

    Examples
    --------
    >>> from sahih_al_bukhari import Bukhari
    >>> bukhari = Bukhari()
    >>> bukhari = Bukhari(data_path="/absolute/path/to/bukhari.json")
    >>> bukhari.get(1)
    >>> bukhari.search("prayer")
    >>> bukhari.getRandom()
    >>> bukhari.getByChapter(1)
    >>> bukhari[0]
    >>> len(bukhari)
    7277
    """

    def __init__(self, data_path: Optional[Union[str, Path]] = None):
        key = _resolve_cache_key(data_path)
        if key not in _cache:
            with _lock:
                if key not in _cache:
                    _cache[key] = _load(data_path)
        self._s = _cache[key]

    # ── Properties ────────────────────────────────────────────────────────── #

    @property
    def metadata(self) -> Metadata:
        return self._s.metadata

    @property
    def chapters(self) -> List[Chapter]:
        return self._s.chapters

    @property
    def length(self) -> int:
        """Mirrors JS ``bukhari.length``."""
        return len(self._s.hadiths)

    # ── Methods — camelCase to match JS exactly ────────────────────────────── #

    def get(self, hadith_id: int) -> Optional[Hadith]:
        """Return the Hadith with the given global ID, or None."""
        return self._s._by_id.get(hadith_id)

    def getByChapter(self, chapter_id: int) -> List[Hadith]:
        """Return all hadiths in *chapter_id*."""
        return self._s._by_chapter.get(chapter_id, [])

    def search(self, query: str, limit: int = 0) -> List[Hadith]:
        """Full-text search across English text and narrator names."""
        q = query.lower()
        results = [
            h for h in self._s.hadiths
            if q in h.text.lower() or q in h.narrator.lower()
        ]
        return results[:limit] if limit > 0 else results

    def getRandom(self) -> Hadith:
        """Return a random Hadith."""
        return random.choice(self._s.hadiths)

    # ── Array-style methods (match JS prototype) ───────────────────────────── #

    def find(self, predicate: Callable[[Hadith], bool]) -> Optional[Hadith]:
        """``bukhari.find(lambda h: h.id == 23)``"""
        return next((h for h in self._s.hadiths if predicate(h)), None)

    def filter(self, predicate: Callable[[Hadith], bool]) -> List[Hadith]:
        """``bukhari.filter(lambda h: h.chapterId == 1)``"""
        return [h for h in self._s.hadiths if predicate(h)]

    def map(self, fn: Callable) -> list:
        """``bukhari.map(lambda h: h.narrator)``"""
        return [fn(h) for h in self._s.hadiths]

    def forEach(self, fn: Callable) -> None:
        """``bukhari.forEach(lambda h, i: print(h.id))``"""
        for i, h in enumerate(self._s.hadiths):
            fn(h, i)

    def slice(self, start: int = 0, end: Optional[int] = None) -> List[Hadith]:
        """``bukhari.slice(0, 10)``"""
        return self._s.hadiths[start:end]

    # ── Python sequence protocol ───────────────────────────────────────────── #

    def __len__(self) -> int:
        return len(self._s.hadiths)

    def __getitem__(self, index):
        return self._s.hadiths[index]

    def __iter__(self) -> Iterator[Hadith]:
        return iter(self._s.hadiths)

    def __repr__(self) -> str:
        return f"<Bukhari hadiths={len(self)} chapters={len(self.chapters)}>"


# ---------------------------------------------------------------------------
# Cache helpers
# ---------------------------------------------------------------------------

def _resolve_cache_key(data_path) -> str:
    if data_path is not None:
        return str(Path(data_path).resolve())
    if _SHARED_JSON.exists():
        return "__shared__"
    return "__cdn__"


def clear_cache(data_path=None) -> None:
    """
    Clear the cache for one path, or the entire cache.

    >>> from sahih_al_bukhari.bukhari import clear_cache
    >>> clear_cache()                              # clear everything
    >>> clear_cache(data_path="/my/bukhari.json")  # clear one entry
    """
    with _lock:
        if data_path is None:
            _cache.clear()
        else:
            _cache.pop(str(Path(data_path).resolve()), None)


# ---------------------------------------------------------------------------
# Loaders
# ---------------------------------------------------------------------------

def _load(data_path=None) -> _Store:
    """Priority: explicit path → shared monorepo file → CDN."""
    if data_path is not None:
        return _load_from_file(Path(data_path))
    if _SHARED_JSON.exists():
        return _load_from_file(_SHARED_JSON)
    return _load_from_cdn()


def _load_from_file(path: Path) -> _Store:
    """
    Load from a local bukhari.json.

    Expected shape (same as bin/bukhari.json in this repo):

        {
          "metadata": { "id": 1, "length": 7277,
                        "arabic":  {"title": ..., "author": ...},
                        "english": {"title": ..., "author": ...} },
          "chapters": [ {"id": 1, "arabic": "...", "english": "..."}, ... ],
          "hadiths":  [ {"id": 1, "chapterId": 1, "arabic": "...",
                         "english": {"narrator": "...", "text": "..."}}, ... ]
        }

    LIMITATIONS
    -----------
    * Must be valid UTF-8 JSON (no BOM, no comments, no trailing commas).
    * All three top-level keys must exist ("metadata", "chapters", "hadiths").
    * "hadiths[].id" must be a unique integer — used as the O(1) lookup key.
    * Entire file is loaded into RAM (~12 MB for the full collection).
    * File is read once and cached; on-disk changes need clear_cache() + restart.
    * Use absolute paths or Path(__file__).parent / "bukhari.json" to avoid
      working-directory surprises with relative paths.
    """
    if not path.exists():
        raise FileNotFoundError(f"bukhari.json not found: {path}")
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if "hadiths" not in data:
        raise ValueError(f"Missing 'hadiths' key in: {path}")
    return _build_store(data)


def _load_from_cdn() -> _Store:
    """Fetch from jsDelivr CDN — same CDN used by the npm package."""
    session = requests.Session()
    meta_r = session.get(f"{CDN_BASE}/meta.json", timeout=30)
    meta_r.raise_for_status()
    meta_json = meta_r.json()

    hadiths_raw: list = []
    for ch in meta_json.get("chapters", []):
        r = session.get(f"{CDN_BASE}/{ch['id']}.json", timeout=30)
        r.raise_for_status()
        hadiths_raw.extend(r.json())

    return _build_store({
        "metadata": meta_json.get("metadata", {}),
        "chapters":  meta_json.get("chapters", []),
        "hadiths":   hadiths_raw,
    })


def _build_store(data: dict) -> _Store:
    return _Store(
        hadiths  = [Hadith(h)  for h in (data.get("hadiths")  or [])],
        chapters = [Chapter(c) for c in (data.get("chapters") or [])],
        metadata = Metadata(data.get("metadata") or {}),
    )
