# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in sahih_al_bukhari.gemspec
gemspec

group :development do
  gem 'rake',      '~> 13.0'
  gem 'test-unit', '~> 3.6'   # FIX: test/unit was removed from Ruby 4.0 stdlib
  gem 'rspec',     '~> 3.0'
  gem 'rubocop',   '~> 1.21'
  gem 'yard',      '~> 0.9'
end
