# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in sahih_al_bukhari.gemspec
gemspec

group :development do
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.0'
  gem 'rubocop', '~> 1.21'
  gem 'yard', '~> 0.9'
end
