// node build.mjs
// 1. Splits bukhari.json into chapters/ folder
// 2. Writes index.browser.js (auto-fetches from CDN, zero config)

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname  = path.dirname(fileURLToPath(import.meta.url));
const data       = JSON.parse(fs.readFileSync(path.join(__dirname, 'bin', 'bukhari.json'), 'utf8'));
const chaptersDir = path.join(__dirname, 'chapters');

// ── 1. chapters/meta.json ─────────────────────────────────────────────────────
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir);
fs.writeFileSync(
  path.join(chaptersDir, 'meta.json'),
  JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }),
  'utf8'
);

// ── 2. chapters/{id}.json — one per chapter ───────────────────────────────────
const byChapter = {};
data.hadiths.forEach(h => {
  if (!byChapter[h.chapterId]) byChapter[h.chapterId] = [];
  byChapter[h.chapterId].push(h);
});
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) {
  fs.writeFileSync(path.join(chaptersDir, `${id}.json`), JSON.stringify(hadiths), 'utf8');
  count++;
}
console.log(`Written ${count} chapter files to chapters/`);

// ── 3. index.browser.js ───────────────────────────────────────────────────────
const src = `// AUTO-GENERATED by build.mjs — do not edit
// Fetches data from jsDelivr CDN automatically. Zero config needed.
// import bukhari from 'sahih-al-bukhari'  → works, auto-loads all data
// import { Bukhari } from 'sahih-al-bukhari' → class for custom data

const CDN = 'https://cdn.jsdelivr.net/npm/sahih-al-bukhari@latest/chapters';

function _makeProxy(hadiths, data) {
  const books = {};
  hadiths.forEach(h => {
    if (!books[h.bookId]) books[h.bookId] = [];
    books[h.bookId].push(h);
  });
  return new Proxy(hadiths, {
    get(target, prop) {
      if (typeof prop === 'symbol') return target[prop];
      if (!isNaN(prop))   return target[parseInt(prop)];
      if (prop in target) return target[prop];
      switch (prop) {
        case 'books':        return books;
        case 'metadata':     return data.metadata;
        case 'chapters':     return data.chapters;
        case 'getByBook':    return (id) => books[id] || [];
        case 'getByChapter': return (id) => hadiths.filter(h => h.chapterId === id);
        case 'search':       return (q)  => hadiths.filter(h =>
          h.english?.text?.toLowerCase().includes(q.toLowerCase()) ||
          h.english?.narrator?.toLowerCase().includes(q.toLowerCase())
        );
        case 'getRandom': return () => hadiths[Math.floor(Math.random() * hadiths.length)];
        case 'length':    return target.length;
        default:          return target[prop];
      }
    },
    ownKeys: (t) => ['length', ...Array.from({length: t.length}, (_, i) => String(i)),
      'books','metadata','chapters','getByBook','getByChapter','search','getRandom']
  });
}

export class Bukhari {
  constructor(data) {
    return _makeProxy(data.hadiths, data);
  }
}

// Fetches all chapters from CDN, returns a full BukhariInstance
async function _fetchAll() {
  const meta = await fetch(CDN + '/meta.json').then(r => r.json());
  const ids  = meta.chapters.map(c => c.id);
  const all  = await Promise.all(ids.map(id => fetch(CDN + '/' + id + '.json').then(r => r.json())));
  return _makeProxy(all.flat(), { metadata: meta.metadata, chapters: meta.chapters });
}

// Default export: awaitable proxy
// - Synchronous array access works AFTER await
// - import bukhari from 'sahih-al-bukhari' then await bukhari
// - OR: const b = await import('sahih-al-bukhari').then(m => m.default)
let   _cache    = null;
const _promise  = _fetchAll().then(b => { _cache = b; return b; });

const _handler = {
  get(_, prop) {
    // await bukhari  →  returns the promise
    if (prop === 'then')   return _promise.then.bind(_promise);
    if (prop === 'catch')  return _promise.catch.bind(_promise);
    if (prop === 'finally')return _promise.finally.bind(_promise);
    // After resolved, proxy directly to the real instance
    if (_cache) {
      const v = _cache[prop];
      return typeof v === 'function' ? v.bind(_cache) : v;
    }
    // Not yet loaded
    return undefined;
  }
};

export default new Proxy({}, _handler);
`;

fs.writeFileSync(path.join(__dirname, 'index.browser.js'), src, 'utf8');
console.log('Written index.browser.js (' + (src.length / 1024).toFixed(1) + ' KB)');
