// node build.mjs
// 1. Splits bin/bukhari.json into chapters/ folder (one file per chapter)
//    — chapters/ is shared with the Python package
// 2. Writes index.browser.js

import fs   from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname   = path.dirname(fileURLToPath(import.meta.url));
const data        = JSON.parse(fs.readFileSync(path.join(__dirname, 'bin', 'bukhari.json'), 'utf8'));
const chaptersDir = path.join(__dirname, 'chapters');

// ── 1. chapters/meta.json ─────────────────────────────────────────────────────
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir);
fs.writeFileSync(
  path.join(chaptersDir, 'meta.json'),
  JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }),
  'utf8'
);

// ── 2. chapters/{id}.json ─────────────────────────────────────────────────────
const byChapter = {};
data.hadiths.forEach(h => {
  if (!byChapter[h.chapterId]) byChapter[h.chapterId] = [];
  byChapter[h.chapterId].push(h);
});
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) {
  fs.writeFileSync(path.join(chaptersDir, `${id}.json`), JSON.stringify(hadiths), 'utf8');
  count++;
}
console.log(`✓ Written ${count} chapter files → chapters/`);
console.log('  (chapters/ is shared between the JS and Python packages)');

// ── 3. index.browser.js ───────────────────────────────────────────────────────
const CDN_VERSION = JSON.parse(fs.readFileSync(path.join(__dirname, 'package.json'), 'utf8')).version;

const browserSrc = `// AUTO-GENERATED by build.mjs — do not edit manually
// sahih-al-bukhari v${CDN_VERSION}
// Loads data from jsDelivr CDN. Works in React, Vue, Vite, webpack.

const CDN = 'https://cdn.jsdelivr.net/npm/sahih-al-bukhari@${CDN_VERSION}/chapters';

function _build(hadiths, meta) {
  const instance = Object.assign([], hadiths, {
    metadata:     meta.metadata,
    chapters:     meta.chapters,
    getByChapter: (id) => hadiths.filter(h => h.chapterId === id),
    get:          (id) => hadiths.find(h => h.id === id),
    search:       (q)  => hadiths.filter(h =>
      h.english?.text?.toLowerCase().includes(q.toLowerCase()) ||
      h.english?.narrator?.toLowerCase().includes(q.toLowerCase())
    ),
    getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)],
  });
  return instance;
}

export class Bukhari {
  constructor(data) {
    return _build(data.hadiths, data);
  }
}

let _cache   = null;
let _promise = null;

export function loadBukhari() {
  if (_cache)   return Promise.resolve(_cache);
  if (_promise) return _promise;
  _promise = fetch(CDN + '/meta.json')
    .then(r => r.json())
    .then(meta => Promise.all(
      meta.chapters.map(c => fetch(CDN + '/' + c.id + '.json').then(r => r.json()))
    ).then(results => {
      _cache = _build(results.flat(), meta);
      return _cache;
    }));
  return _promise;
}

export default loadBukhari();
`;

fs.writeFileSync(path.join(__dirname, 'index.browser.js'), browserSrc, 'utf8');
console.log(`✓ Written index.browser.js`);
console.log('');
console.log('Build complete!');
