// node scripts/build.mjs
// 1. Reads data/bukhari.json or data/bukhari.json.gz
// 2. Splits into data/chapters/ (one file per chapter) — for CDN reference
// 3. Writes src/index.browser.js

import fs   from 'fs';
import zlib from 'zlib';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const dataDir   = path.join(ROOT, 'data');

// ── Step 1: Load data/bukhari.json (always the source of truth) ──────────────
const jsonPath = path.join(dataDir, 'bukhari.json');
const gzPath   = path.join(dataDir, 'bukhari.json.gz');

if (!fs.existsSync(jsonPath)) {
  throw new Error('data/bukhari.json not found. Place your bukhari.json in the data/ folder.');
}
console.log('✓ Reading data/bukhari.json ...');
const raw  = fs.readFileSync(jsonPath);
const data = JSON.parse(raw.toString('utf8'));
console.log(`  hadiths : ${data.hadiths.length.toLocaleString()}`);
console.log(`  chapters: ${data.chapters.length.toLocaleString()}`);
console.log('');

// ── Step 2: Always recompress json → gz (never stale) ─────────────────────────
console.log('✓ Compressing data/bukhari.json → data/bukhari.json.gz ...');
const compressed = zlib.gzipSync(raw, { level: 9 });
fs.writeFileSync(gzPath, compressed);
console.log(`  before : ${(raw.length        / 1024 / 1024).toFixed(2)} MB`);
console.log(`  after  : ${(compressed.length / 1024 / 1024).toFixed(2)} MB`);
console.log(`  saved  : ${((1 - compressed.length / raw.length) * 100).toFixed(0)}%`);
console.log('');

// ── 1. data/chapters/meta.json ────────────────────────────────────────────────
const chaptersDir = path.join(dataDir, 'chapters');
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir, { recursive: true });
fs.writeFileSync(
  path.join(chaptersDir, 'meta.json'),
  JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }),
  'utf8'
);

// ── 2. data/chapters/{id}.json ────────────────────────────────────────────────
const byChapter = {};
data.hadiths.forEach(h => {
  if (!byChapter[h.chapterId]) byChapter[h.chapterId] = [];
  byChapter[h.chapterId].push(h);
});
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) {
  fs.writeFileSync(path.join(chaptersDir, `${id}.json`), JSON.stringify(hadiths), 'utf8');
  count++;
}
console.log(`✓ Written ${count} chapter files → data/chapters/`);
console.log('');

// ── 3. src/index.browser.js ───────────────────────────────────────────────────
const version    = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
const CDN_FILE   = `https://cdn.jsdelivr.net/npm/sahih-al-bukhari@${version}/data/bukhari.json.gz`;

const browserSrc = `// AUTO-GENERATED by scripts/build.mjs — do not edit manually
// sahih-al-bukhari v${version}
// Fetches data/bukhari.json.gz from CDN. Works in React, Vue, Vite, webpack.

const CDN_FILE = '${CDN_FILE}';

function _build(hadiths, meta) {
  return Object.assign([], hadiths, {
    metadata:     meta.metadata,
    chapters:     meta.chapters,
    getByChapter: (id) => hadiths.filter(h => h.chapterId === id),
    get:          (id) => hadiths.find(h => h.id === id),
    search:       (q, limit = 0) => {
      const ql = q.toLowerCase();
      const r  = hadiths.filter(h =>
        h.english?.text?.toLowerCase().includes(ql) ||
        h.english?.narrator?.toLowerCase().includes(ql)
      );
      return limit > 0 ? r.slice(0, limit) : r;
    },
    getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)],
  });
}

export class Bukhari {
  constructor(data) { return _build(data.hadiths, data); }
}

let _cache = null, _promise = null;

export function loadBukhari() {
  if (_cache)   return Promise.resolve(_cache);
  if (_promise) return _promise;
  _promise = fetch(CDN_FILE)
    .then(r => r.arrayBuffer())
    .then(buf => {
      const stream = new DecompressionStream('gzip');
      const writer = stream.writable.getWriter();
      const reader = stream.readable.getReader();
      writer.write(new Uint8Array(buf)); writer.close();
      const chunks = [];
      return (function pump() {
        return reader.read().then(({ done, value }) => {
          if (done) {
            const text = new TextDecoder().decode(new Uint8Array(chunks.reduce((a,b)=>[...a,...b],[])));
            _cache = _build(JSON.parse(text).hadiths, JSON.parse(text));
            return _cache;
          }
          chunks.push(value); return pump();
        });
      })();
    });
  return _promise;
}

export default loadBukhari();
`;

fs.writeFileSync(path.join(ROOT, 'src', 'index.browser.js'), browserSrc, 'utf8');
console.log('✓ Written src/index.browser.js');
console.log('');

// ── Step 5: Copy .gz into python/sahih_al_bukhari/data/ ──────────────────────
// This makes Poetry include it in the wheel when running python -m build
const pyDataDir = path.join(ROOT, 'python', 'sahih_al_bukhari', 'data');
fs.mkdirSync(pyDataDir, { recursive: true });
fs.copyFileSync(gzPath, path.join(pyDataDir, 'bukhari.json.gz'));
console.log('✓ Copied bukhari.json.gz → python/sahih_al_bukhari/data/');
console.log('');
console.log('Build complete!');
