// node scripts/build.mjs
// 1. Reads data/bukhari.json or data/bukhari.json.gz
// 2. Splits into data/chapters/ (one file per chapter) — for CDN reference
// 3. Writes src/index.browser.js

import fs   from 'fs';
import zlib from 'zlib';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT      = path.resolve(__dirname, '..');
const dataDir   = path.join(ROOT, 'data');

// ── Load bukhari data (gz preferred, json fallback) ───────────────────────────
function loadData() {
  const gzPath   = path.join(dataDir, 'bukhari.json.gz');
  const jsonPath = path.join(dataDir, 'bukhari.json');
  if (fs.existsSync(gzPath)) {
    console.log('✓ Reading data/bukhari.json.gz');
    return JSON.parse(zlib.gunzipSync(fs.readFileSync(gzPath)).toString('utf8'));
  }
  if (fs.existsSync(jsonPath)) {
    console.log('✓ Reading data/bukhari.json');
    return JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
  }
  throw new Error('No data file found. Place bukhari.json or bukhari.json.gz in data/');
}

const data = loadData();

// ── Optional: gzip bukhari.json if not already gzipped ───────────────────────
const jsonPath = path.join(dataDir, 'bukhari.json');
const gzPath   = path.join(dataDir, 'bukhari.json.gz');
if (fs.existsSync(jsonPath) && !fs.existsSync(gzPath)) {
  const compressed = zlib.gzipSync(fs.readFileSync(jsonPath), { level: 9 });
  fs.writeFileSync(gzPath, compressed);
  const before = fs.statSync(jsonPath).size;
  const after  = compressed.length;
  console.log(`✓ Compressed: bukhari.json (${(before/1024/1024).toFixed(1)}MB) → bukhari.json.gz (${(after/1024/1024).toFixed(1)}MB)`);
}

// ── 1. data/chapters/meta.json ────────────────────────────────────────────────
const chaptersDir = path.join(dataDir, 'chapters');
if (!fs.existsSync(chaptersDir)) fs.mkdirSync(chaptersDir, { recursive: true });
fs.writeFileSync(
  path.join(chaptersDir, 'meta.json'),
  JSON.stringify({ metadata: data.metadata, chapters: data.chapters, total: data.hadiths.length }),
  'utf8'
);

// ── 2. data/chapters/{id}.json ────────────────────────────────────────────────
const byChapter = {};
data.hadiths.forEach(h => {
  if (!byChapter[h.chapterId]) byChapter[h.chapterId] = [];
  byChapter[h.chapterId].push(h);
});
let count = 0;
for (const [id, hadiths] of Object.entries(byChapter)) {
  fs.writeFileSync(path.join(chaptersDir, `${id}.json`), JSON.stringify(hadiths), 'utf8');
  count++;
}
console.log(`✓ Written ${count} chapter files → data/chapters/`);

// ── 3. src/index.browser.js ───────────────────────────────────────────────────
const version    = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8')).version;
const CDN_FILE   = `https://cdn.jsdelivr.net/npm/sahih-al-bukhari@${version}/data/bukhari.json.gz`;

const browserSrc = `// AUTO-GENERATED by scripts/build.mjs — do not edit manually
// sahih-al-bukhari v${version}
// Fetches data/bukhari.json.gz from CDN. Works in React, Vue, Vite, webpack.

const CDN_FILE = '${CDN_FILE}';

function _build(hadiths, meta) {
  return Object.assign([], hadiths, {
    metadata:     meta.metadata,
    chapters:     meta.chapters,
    getByChapter: (id) => hadiths.filter(h => h.chapterId === id),
    get:          (id) => hadiths.find(h => h.id === id),
    search:       (q, limit = 0) => {
      const ql = q.toLowerCase();
      const r  = hadiths.filter(h =>
        h.english?.text?.toLowerCase().includes(ql) ||
        h.english?.narrator?.toLowerCase().includes(ql)
      );
      return limit > 0 ? r.slice(0, limit) : r;
    },
    getRandom: () => hadiths[Math.floor(Math.random() * hadiths.length)],
  });
}

export class Bukhari {
  constructor(data) { return _build(data.hadiths, data); }
}

let _cache = null, _promise = null;

export function loadBukhari() {
  if (_cache)   return Promise.resolve(_cache);
  if (_promise) return _promise;
  _promise = fetch(CDN_FILE)
    .then(r => r.arrayBuffer())
    .then(buf => {
      const stream = new DecompressionStream('gzip');
      const writer = stream.writable.getWriter();
      const reader = stream.readable.getReader();
      writer.write(new Uint8Array(buf)); writer.close();
      const chunks = [];
      return (function pump() {
        return reader.read().then(({ done, value }) => {
          if (done) {
            const text = new TextDecoder().decode(new Uint8Array(chunks.reduce((a,b)=>[...a,...b],[])));
            _cache = _build(JSON.parse(text).hadiths, JSON.parse(text));
            return _cache;
          }
          chunks.push(value); return pump();
        });
      })();
    });
  return _promise;
}

export default loadBukhari();
`;

fs.writeFileSync(path.join(ROOT, 'src', 'index.browser.js'), browserSrc, 'utf8');
console.log('✓ Written src/index.browser.js');
console.log('');
console.log('Build complete!');
